import { getToken, getUser, saveAuthData, clearAuthData, isLoggedIn } from "./apiClient";
import {
  authApi,
  signupApi,
  verifyOtpApi,
  loginApi,
  sendLoginOtpApi,
  verifyLoginOtpApi,
  logoutApi,
  deleteUserApi,
  forgotPasswordApi,
  resetPasswordApi,
  changePasswordApi,
  getUserProfileApi,
  updateProfileApi,
  getAddressesApi,
  addAddressApi,
} from "./authApi";

export {
  getToken,
  getUser,
  saveAuthData,
  clearAuthData,
  isLoggedIn,
  authApi,
  signupApi,
  verifyOtpApi,
  loginApi,
  sendLoginOtpApi,
  verifyLoginOtpApi,
  logoutApi,
  deleteUserApi,
  forgotPasswordApi,
  resetPasswordApi,
  changePasswordApi,
  getUserProfileApi,
  updateProfileApi,
  getAddressesApi,
  addAddressApi,
};

export const authService = {
  getToken,
  getUser,
  saveAuthData,
  clearAuthData,
  isLoggedIn,
  signup: signupApi,
  verifyOtp: verifyOtpApi,
  login: loginApi,
  sendLoginOtp: sendLoginOtpApi,
  verifyLoginOtp: verifyLoginOtpApi,
  logout: logoutApi,
  deleteUser: deleteUserApi,
  forgotPassword: forgotPasswordApi,
  resetPassword: resetPasswordApi,
  changePassword: changePasswordApi,
  getUserProfile: getUserProfileApi,
  updateProfile: updateProfileApi,
  getAddresses: getAddressesApi,
  addAddress: addAddressApi,
};

export default authApi;
